namespace FrameShift.Core.Actions;

public static class ActionOptionKeys
{
    public const string Target = "target";
    public const string Profile = "profile";
    public const string TargetSizeBytes = "target-size-bytes";
    public const string StartTime = "start";
    public const string EndTime = "end";
    public const string Duration = "duration";
    public const string StartFrame = "start-frame";
    public const string EndFrame = "end-frame";
    public const string WorkingFile = "working-file";
    public const string WorkingRoot = "working-root";
    public const string CropX = "crop-x";
    public const string CropY = "crop-y";
    public const string CropWidth = "crop-width";
    public const string CropHeight = "crop-height";
    public const string ResizeWidth = "resize-width";
    public const string ResizeHeight = "resize-height";
    public const string ImageToPdfSettings = "image-to-pdf-settings";
    public const string GifResolution = "gif-resolution";
    public const string GifFps = "gif-fps";
    public const string GifQuality = "gif-quality";
    public const string IconSizes = "icon-sizes";
    public const string IconFitMode = "icon-fit-mode";
    public const string IconBackground = "icon-background";
    public const string PitchSemitones = "pitch-semitones";
    public const string PitchKeepDuration = "pitch-keep-duration";
    public const string SpeedFactor = "speed-factor";
    public const string SpeedKeepPitch = "speed-keep-pitch";
    public const string RotateAngle = "rotate-angle";
    public const string FlipHorizontal = "flip-h";
    public const string FlipVertical = "flip-v";
    public const string InterpolateFps = "interpolate-fps";
    public const string InterpolateModelId = "interpolate-model-id";
    public const string InterpolateMultiplier = "interpolate-multiplier";
    public const string InterpolatePlaybackDivisor = "interpolate-playback-divisor";
    public const string InterpolateSlowMotionKeepPitch = "interpolate-slowmotion-keep-pitch";
    public const string InterpolateSlowMotionRemoveAudio = "interpolate-slowmotion-remove-audio";
    public const string InterpolatePipeline = "interpolate-pipeline";
    public const string Stems = "stems";
    public const string SeparateEngine = "separate-engine";
    public const string NoiseStrength = "noise-strength";
    public const string ProcessStereoAudio = "process-stereo-audio";
    public const string BackgroundRemovalModel = "rmbg-model";
    public const string UpscaleModel = "upscale-model";
    public const string UpscaleScale = "upscale-scale";
    public const string UpscaleTargetWidth = "upscale-target-width";
    public const string UpscaleTargetHeight = "upscale-target-height";
}
