using System;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;

namespace FrameShift.Core.AI.CreateSubtitles;

internal static class CreateSubtitlesAssFormatter
{
    private const string HighlightCloseTag = "{\\r}";

    public static string Format(
        SubtitleProject project,
        CreateSubtitlesAssPreset preset = CreateSubtitlesAssPreset.Classic)
    {
        return Format(project, preset, CreateSubtitlesAssLayout.Default);
    }

    public static string Format(
        SubtitleProject project,
        CreateSubtitlesAssPreset preset,
        CreateSubtitlesAssLayout layout)
    {
        var builder = new StringBuilder(project.Segments.Count * 96);
        builder.AppendLine("[Script Info]");
        builder.AppendLine("; Script generated by FrameShift");
        builder.AppendLine("Title: FrameShift Subtitles");
        builder.AppendLine("ScriptType: v4.00+");
        builder.AppendLine("WrapStyle: 0");
        builder.AppendLine("ScaledBorderAndShadow: yes");
        builder.AppendLine("YCbCr Matrix: None");
        builder.AppendLine($"PlayResX: {layout.PlayResX.ToString(CultureInfo.InvariantCulture)}");
        builder.AppendLine($"PlayResY: {layout.PlayResY.ToString(CultureInfo.InvariantCulture)}");
        builder.AppendLine();
        builder.AppendLine("[V4+ Styles]");
        builder.AppendLine("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding");
        builder.AppendLine(string.Create(
            CultureInfo.InvariantCulture,
            $"Style: Default,{layout.FontName},{layout.FontSize},{FormatStyleAssColor(layout.PrimaryColor)},{FormatStyleAssColor(layout.HighlightColor)},{FormatStyleAssColor(layout.OutlineColor)},{FormatStyleAssColorWithAlpha(layout.ShadowColor, 0x64)},0,0,0,0,100,100,0,0,1,{FormatAssNumber(layout.Outline)},{FormatAssNumber(layout.Shadow)},{layout.Alignment},{layout.MarginL},{layout.MarginR},{layout.MarginV},1"));
        builder.AppendLine();
        builder.AppendLine("[Events]");
        builder.AppendLine("Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text");

        foreach (var segment in project.Segments)
        {
            var effectivePreset = ResolveEffectivePreset(segment, preset);

            switch (effectivePreset)
            {
                case CreateSubtitlesAssPreset.WordHighlight:
                    AppendWordHighlightSegment(builder, segment, layout);
                    break;

                case CreateSubtitlesAssPreset.ProgressiveReveal:
                    AppendProgressiveRevealSegment(builder, segment);
                    break;

                default:
                    AppendClassicSegment(builder, segment);
                    break;
            }
        }

        return builder.ToString();
    }

    internal static CreateSubtitlesAssPreset ResolveEffectivePreset(SubtitleSegment segment, CreateSubtitlesAssPreset requestedPreset)
    {
        return segment.HasReliableWordAlignment
            ? requestedPreset
            : CreateSubtitlesAssPreset.Classic;
    }

    private static void AppendClassicSegment(StringBuilder builder, SubtitleSegment segment)
    {
        AppendDialogueLine(builder, segment.DisplayStart, segment.End, EscapeText(segment.Text));
    }

    private static void AppendWordHighlightSegment(StringBuilder builder, SubtitleSegment segment, CreateSubtitlesAssLayout layout)
    {
        var displayStartSeconds = segment.DisplayStart.TotalSeconds;
        var plainWords = segment.Words.Select(static item => item.Text).ToArray();
        for (var index = 0; index < segment.Words.Count; index++)
        {
            var word = segment.Words[index];
            AppendDialogueLine(
                builder,
                TimeSpan.FromSeconds(index == 0 ? Math.Max(word.StartSeconds, displayStartSeconds) : word.StartSeconds),
                TimeSpan.FromSeconds(word.EndSeconds),
                BuildWrappedLine(
                    plainWords,
                    segment.Words.Select((item, itemIndex) =>
                        itemIndex == index
                            ? $"{BuildHighlightOpenTag(layout.HighlightColor)}{EscapeText(item.Text)}{HighlightCloseTag}"
                            : EscapeText(item.Text)).ToArray()));
        }
    }

    private static void AppendProgressiveRevealSegment(StringBuilder builder, SubtitleSegment segment)
    {
        var displayStartSeconds = segment.DisplayStart.TotalSeconds;
        for (var index = 0; index < segment.Words.Count; index++)
        {
            var word = segment.Words[index];
            AppendDialogueLine(
                builder,
                TimeSpan.FromSeconds(index == 0 ? Math.Max(word.StartSeconds, displayStartSeconds) : word.StartSeconds),
                TimeSpan.FromSeconds(word.EndSeconds),
                BuildWrappedLine(
                    segment.Words.Take(index + 1).Select(static item => item.Text).ToArray(),
                    segment.Words.Take(index + 1).Select(item => EscapeText(item.Text)).ToArray()));
        }
    }

    private static void AppendDialogueLine(StringBuilder builder, TimeSpan start, TimeSpan end, string text)
    {
        var safeEnd = end <= start
            ? start + TimeSpan.FromMilliseconds(10)
            : end;
        builder
            .Append("Dialogue: 0,")
            .Append(FormatTimestamp(start))
            .Append(',')
            .Append(FormatTimestamp(safeEnd))
            .Append(",Default,,0,0,0,,")
            .Append(text)
            .AppendLine();
    }

    private static string BuildWrappedLine(string[] plainWords, string[] renderedWords)
    {
        if (plainWords.Length == 0)
        {
            return string.Empty;
        }

        var plainText = string.Join(" ", plainWords).Trim();
        if (plainText.Length <= 42 || plainWords.Length == 1)
        {
            return string.Join(" ", renderedWords).Trim();
        }

        var midpoint = plainText.Length / 2d;
        var bestBreakIndex = -1;
        var bestDistance = double.MaxValue;
        var currentLength = 0;

        for (var index = 0; index < plainWords.Length - 1; index++)
        {
            currentLength += plainWords[index].Length;
            var distance = Math.Abs(currentLength - midpoint);
            if (distance < bestDistance)
            {
                bestDistance = distance;
                bestBreakIndex = index;
            }

            currentLength += 1;
        }

        if (bestBreakIndex < 0)
        {
            return string.Join(" ", renderedWords).Trim();
        }

        var firstLine = string.Join(" ", renderedWords.Take(bestBreakIndex + 1)).Trim();
        var secondLine = string.Join(" ", renderedWords.Skip(bestBreakIndex + 1)).Trim();
        return $"{firstLine}\\N{secondLine}";
    }

    private static string EscapeText(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return string.Empty;
        }

        return text
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("{", "\\{", StringComparison.Ordinal)
            .Replace("}", "\\}", StringComparison.Ordinal)
            .Replace("\r\n", "\\N", StringComparison.Ordinal)
            .Replace("\n", "\\N", StringComparison.Ordinal)
            .Replace("\r", "\\N", StringComparison.Ordinal);
    }

    private static string FormatTimestamp(TimeSpan timeSpan)
    {
        if (timeSpan < TimeSpan.Zero)
        {
            timeSpan = TimeSpan.Zero;
        }

        var totalCentiseconds = (long)Math.Round(timeSpan.TotalMilliseconds / 10d, MidpointRounding.AwayFromZero);
        var hours = totalCentiseconds / 360000;
        var remaining = totalCentiseconds % 360000;
        var minutes = remaining / 6000;
        remaining %= 6000;
        var seconds = remaining / 100;
        var centiseconds = remaining % 100;

        return string.Create(
            CultureInfo.InvariantCulture,
            $"{hours}:{minutes:00}:{seconds:00}.{centiseconds:00}");
    }

    private static string FormatAssNumber(double value)
    {
        return value.ToString("0.##", CultureInfo.InvariantCulture);
    }

    private static string BuildHighlightOpenTag(Color color)
    {
        return string.Create(CultureInfo.InvariantCulture, $"{{\\c{FormatTagAssColor(color)}\\b1}}");
    }

    private static string FormatTagAssColor(Color color)
    {
        return string.Create(CultureInfo.InvariantCulture, $"&H00{color.B:X2}{color.G:X2}{color.R:X2}&");
    }

    private static string FormatStyleAssColor(Color color)
    {
        return string.Create(CultureInfo.InvariantCulture, $"&H00{color.B:X2}{color.G:X2}{color.R:X2}");
    }

    private static string FormatStyleAssColorWithAlpha(Color color, byte alpha)
    {
        return string.Create(CultureInfo.InvariantCulture, $"&H{alpha:X2}{color.B:X2}{color.G:X2}{color.R:X2}");
    }
}

internal sealed record CreateSubtitlesAssLayout(
    int PlayResX,
    int PlayResY,
    string FontName,
    int FontSize,
    Color PrimaryColor,
    Color HighlightColor,
    Color OutlineColor,
    Color ShadowColor,
    int MarginL,
    int MarginR,
    int MarginV,
    double Outline,
    double Shadow,
    int Alignment)
{
    public static CreateSubtitlesAssLayout Default { get; } = new(
        1920,
        1080,
        "Arial",
        54,
        Color.White,
        Color.Yellow,
        Color.Black,
        Color.Black,
        90,
        90,
        54,
        2.2d,
        0.8d,
        2);

    public static CreateSubtitlesAssLayout ForVideo(int videoWidth, int videoHeight)
    {
        if (videoWidth <= 0 || videoHeight <= 0)
        {
            return Default;
        }

        var scale = Math.Min(videoWidth / 1920d, videoHeight / 1080d);
        if (double.IsNaN(scale) || double.IsInfinity(scale) || scale <= 0d)
        {
            scale = 1d;
        }

        scale = Math.Clamp(scale, 0.55d, 2.5d);

        return new CreateSubtitlesAssLayout(
            videoWidth,
            videoHeight,
            Default.FontName,
            ScaleInt(Default.FontSize, scale, 28),
            Default.PrimaryColor,
            Default.HighlightColor,
            Default.OutlineColor,
            Default.ShadowColor,
            ScaleInt(Default.MarginL, scale, 42),
            ScaleInt(Default.MarginR, scale, 42),
            ScaleInt(Default.MarginV, scale, 28),
            Math.Round(Default.Outline * scale, 2, MidpointRounding.AwayFromZero),
            Math.Round(Default.Shadow * scale, 2, MidpointRounding.AwayFromZero),
            Default.Alignment);
    }

    private static int ScaleInt(int value, double scale, int minimum)
    {
        return Math.Max(minimum, (int)Math.Round(value * scale, MidpointRounding.AwayFromZero));
    }
}
